### ISSUE TITLE
output of libpracmln-build is not correct

### ISSUE THREAD

**Issue by bbferka** [danielnyga/pracmln#9]
I installed pracmln using pip install pracmln --user (Ubuntu 16.06, Python 2.7)

After fixing the CMake ( #8 ) and running libpracmln-build everything compiles fine but the output of the script is wroing:

```
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/presentation/.local/share/pracmln/libpracmln/install/include
-- Up-to-date: /home/presentation/.local/share/pracmln/libpracmln/install/include/pracmln
-- Up-to-date: /home/presentation/.local/share/pracmln/libpracmln/install/include/pracmln/mln.h
-- Installing: /home/presentation/.local/share/pracmln/libpracmln/install/lib/libpracmln.so

export LD_LIBRARY_PATH="/home/presentation/libpracmln/install/lib:${LD_LIBRARY_PATH}"
export LIBRARY_PATH="/home/presentation/libpracmln/install/lib:${LIBRARY_PATH}"
export CPATH="/home/presentation/libpracmln/install/include:${CPATH}"
export CMAKE_LIBRARY_PATH="/home/presentation/libpracmln/install/lib:${CMAKE_LIBRARY_PATH}"
export CMAKE_INCLUDE_PATH="/home/presentation/libpracmln/install/include:${CMAKE_INCLUDE_PATH}"
```
The libpracmln folder created by the script only contains a build folder. But not the install. The install location is set by the CMAKE_INSTALL_PREFIX. So I added that options as well to #8

**Comment by gautamshetty** [comment]
HI @bbferka How are you running libpracmln-build, I get "command not found" error when I run it.
I tried libpracmln.py install but getting "ImportError: No module named dnutils" error. Thanks.

**Comment by gautamshetty** [comment]
HI @bbferka How are you running libpracmln-build, I get "command not found" error when I run it.
I tried libpracmln.py install but getting "ImportError: No module named dnutils" error. Thanks. I have run "python setup.py install" and that is successful.

**Comment by danielnyga** [comment]
thanks for the fix @bbferka I merged the pull request.

**Comment by danielnyga** [comment]
@gautamshetty Try installing the dependencies from the `requirements.txt` in either `python2` or `python3` -- depending on what Python version you use -- directories when not installing it from the PyPI:

`pip install -r requirements.txt`

**Comment by gautamshetty** [comment]
Thanks @danielnyga That worked!! I am able to run the GUI tools now.

**Comment by ChanakaThushitha** [comment]
@danielnyga 

I followed the steps given on http://www.pracmln.org/installation.html to install Pracmln. The next thing I have to do is to follow the instructions given under "C++ bindings" sub-topic. 

Even though the requirements of C++ bindings are
-Linux OS (tested on Ubuntu 14.04, 16.04 with Python 2.7 and Python 3.5)
-libboost-python
-libpython-dev

, "libboost-python" and "libpython-dev" cound not be downloaded to Python and my operating system is Windows 10.  

1) Can I run Pracmln successfully in Windows? 

2) Do I need to do "C++ bindings" if I am not using C"" language for coding? 

3) Do I need to run "libpracmln-build"?  If so, how to run "libpracmln-build"?

**Comment by bbferka** [comment]
@ChanakaThushitha  C++ bininds are optional
